[package]
name = "gexgit2"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = { version = "0.18.0", features = []}
url = "2.4.1"
derive_builder = "0.12.0"
thiserror = "1.0.48"